
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrkxgqjyucwgfioffhkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlya3hncWp5dWN3Z2Zpb2ZmaGtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0ODEwNTMsImV4cCI6MjA3MTA1NzA1M30.Ut_HmbMXJTPhdgY4PWoNth8U6OwpGIhdSDNAVjiENkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
